# Generated by Django 6.0.7 on 2026-08-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20),
        ),
    ]
